# Generated by Django 5.0 on 2024-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
